#===-- Default Config - A CMake file for a machine default config  ------------------------------------*- CMake -*-===//
#
# This file may be hand crafted or generated by the build system as-is; and is tracked by the version system.
#
#===---------------------------------------------------------------------------------------------------------------===//
#/
#/ \file
#/ Contains the current configuration, exported using the SET_AND_EXPORT and SET_AND_EXPORT_FORCE directives. This file
#/ has a correct CMake syntax, therefore, it can be copied and used directly as an initial machine configuration.
#/
#/ Default configurations for machines in the Architecture folder may be hand crafted from a generated file by the build
#/ system, and they are tracked by the build system. They are not "automatically updated", and they are part of the
#/ build system. As such, they must be high quality as the whole project.
#/
#/ This is the default header and all files must contain it, replacing the header of the automatically generated and
#/ updated files by the build system (known as "seeds").
#/
#===---------------------------------------------------------------------------------------------------------------===//

# This is a recognizable name for the machine
SET(MACHINE_NAME "ARM RealView Platform Baseboard Explore for Cortex-A9")
